#!/bin/bash

# ==============================================================================
# UniFi Network OS Auto-Dynamic Enforced Setup
# ==============================================================================
# This script enforces strict requirements for security and stability.
# It will ABORT if any critical check fails.
# ==============================================================================

set -e # Exit immediately if a command exits with a non-zero status

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${INSTALL_DIR}/.env"
REQUIRED_DISK_GB=10
REQUIRED_RAM_GB=1.5
REQUIRED_PORTS=("8443" "8080" "21" "27017" "3478")

# ------------------------------------------------------------------------------
# Helper Functions
# ------------------------------------------------------------------------------

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

enforce_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (sudo)."
        log_error "Docker network bindings and port mapping require elevated privileges."
        exit 1
    fi
    log_info "Root privileges verified."
}

check_docker() {
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first."
        exit 1
    fi
    if ! docker info &> /dev/null; then
        log_error "Docker daemon is not running. Start Docker and try again."
        exit 1
    fi
    log_success "Docker daemon is active."
}

check_resources() {
    log_info "Enforcing hardware requirements..."
    
    # Check Disk Space
    local available_disk=$(df -BG "$INSTALL_DIR" | awk 'NR==2 {print $4}' | sed 's/G//')
    if (( $(echo "$available_disk < $REQUIRED_DISK_GB" | bc -l) )); then
        log_error "Insufficient disk space. Found: ${available_disk}GB, Required: ${REQUIRED_DISK_GB}GB"
        exit 1
    fi
    log_success "Disk space OK (${available_disk}GB available)."

    # Check RAM
    local total_ram=$(free -g | awk 'NR==2 {print $2}')
    if (( $(echo "$total_ram < $REQUIRED_RAM_GB" | bc -l) )); then
        log_error "Insufficient RAM. Found: ${total_ram}GB, Required: ${REQUIRED_RAM_GB}GB"
        exit 1
    fi
    log_success "Memory OK (${total_ram}GB available)."
}

check_ports() {
    log_info "Enforcing port availability..."
    local port_conflict=0
    
    for port in "${REQUIRED_PORTS[@]}"; do
        if ss -tuln | grep -q ":$port "; then
            log_error "Port $port is already in use. Cannot proceed."
            port_conflict=1
        fi
    done

    if [ $port_conflict -eq 1 ]; then
        log_error "Port conflict detected. Please free up the required ports and retry."
        exit 1
    fi
    log_success "All required ports are available."
}

generate_secure_env() {
    log_info "Generating secure environment configuration..."
    
    # Generate random passwords
    MONGO_ROOT_PASS=$(openssl rand -base64 32 | tr -d '/=+' | head -c 32)
    MONGO_USER_PASS=$(openssl rand -base64 32 | tr -d '/=+' | head -c 32)
    FTP_PASS=$(openssl rand -base64 24 | tr -d '/=+' | head -c 24)
    
    # Detect Server IP dynamically
    SERVER_IP=$(hostname -I | awk '{print $1}')
    if [ -z "$SERVER_IP" ]; then
        log_warn "Could not auto-detect IP. Defaulting to 127.0.0.1 (Localhost only)"
        SERVER_IP="127.0.0.1"
    fi

    cat > "$ENV_FILE" <<EOFINNER
# Auto-generated by Enforced Setup Script - $(date)
# DO NOT EDIT MANUALLY UNLESS NECESSARY

# Network Settings
SERVER_IP=${SERVER_IP}

# MongoDB Credentials (Auto-Generated Secure)
MONGO_ROOT_USER=root
MONGO_ROOT_PASS=${MONGO_ROOT_PASS}
MONGO_USER=unifi
MONGO_PASS=${MONGO_USER_PASS}

# FTP Credentials (Auto-Generated Secure)
FTP_USER=unifi
FTP_PASS=${FTP_PASS}

# Resource Limits
MEM_LIMIT=2G
CPU_LIMIT=2.0
EOFINNER

    # Verify generation
    if [ ! -f "$ENV_FILE" ] || [ ! -s "$ENV_FILE" ]; then
        log_error "Failed to generate .env file. Aborting."
        exit 1
    fi
    
    log_success "Secure environment file generated at ${ENV_FILE}"
    echo ""
    log_warn "SAVE THESE CREDENTIALS SECURELY:"
    echo "----------------------------------------"
    echo "MongoDB Root Pass: ${MONGO_ROOT_PASS}"
    echo "MongoDB User Pass: ${MONGO_USER_PASS}"
    echo "FTP Password     : ${FTP_PASS}"
    echo "Server IP        : ${SERVER_IP}"
    echo "----------------------------------------"
}

create_directories() {
    log_info "Creating enforced directory structure..."
    mkdir -p "${INSTALL_DIR}/unifi-data"
    mkdir -p "${INSTALL_DIR}/unifi-db-data"
    mkdir -p "${INSTALL_DIR}/unifi-storage"
    mkdir -p "${INSTALL_DIR}/vsftpd-config"
    mkdir -p "${INSTALL_DIR}/vsftpd-data/unifi"
    
    # Set strict permissions
    chmod 750 "${INSTALL_DIR}/unifi-data"
    chmod 750 "${INSTALL_DIR}/unifi-db-data"
    chmod 770 "${INSTALL_DIR}/unifi-storage"
    chmod 750 "${INSTALL_DIR}/vsftpd-config"
    chmod 700 "${INSTALL_DIR}/vsftpd-data"
    
    log_success "Directory structure created with secure permissions."
}

deploy_containers() {
    log_info "Deploying containers with health checks enabled..."
    
    cd "$INSTALL_DIR"
    
    # Pull images first to ensure validity
    docker compose pull || {
        log_error "Failed to pull Docker images. Check internet connection."
        exit 1
    }

    # Start services
    docker compose up -d
    
    log_info "Waiting for services to initialize (max 60s)..."
    
    # Enforcement: Health Check Loop
    local max_wait=60
    local waited=0
    local healthy=0
    
    while [ $waited -lt $max_wait ]; do
        sleep 5
        waited=$((waited + 5))
        
        # Check if UniFi container is running and healthy
        if docker compose ps unifi | grep -q "healthy\|running"; then
             # Basic check: is the process actually up?
             if docker compose exec -T unifi ps aux | grep -q "java"; then
                healthy=1
                break
             fi
        fi
        log_info "Still waiting for UniFi controller... (${waited}s/${max_wait}s)"
    done

    if [ $healthy -eq 0 ]; then
        log_error "Enforcement Failed: UniFi Controller did not become healthy within ${max_wait} seconds."
        log_info "Rolling back deployment..."
        docker compose down
        log_error "Please check logs: docker compose logs unifi"
        exit 1
    fi

    log_success "Deployment enforced and verified successful!"
}

show_access_info() {
    source "$ENV_FILE"
    echo ""
    log_success "=== DEPLOYMENT COMPLETE ==="
    echo "UniFi Network OS URL: https://${SERVER_IP}:8443"
    echo "FTP Server Address:   ftp://${SERVER_IP}:21"
    echo "FTP Username:         ${FTP_USER}"
    echo "Shared Storage Path:  ${INSTALL_DIR}/unifi-storage"
    echo ""
    log_info "To view logs: docker compose logs -f"
    log_info "To stop:      docker compose down"
}

# ------------------------------------------------------------------------------
# Main Execution Flow
# ------------------------------------------------------------------------------

echo "=========================================="
echo "  UniFi Network OS Enforced Installer"
echo "=========================================="

enforce_root
check_docker
check_resources
check_ports
generate_secure_env
create_directories
deploy_containers
show_access_info
