storage:
  wiredTiger:
    cacheSizeGB: 0.25
    journal:
      commitIntervalMs: 100
systemLog:
  destination: file
  path: /data/db/mongod.log
  logAppend: true
net:
  port: 27017
  bindIp: 0.0.0.0
processManagement:
  timeZoneInfo: /usr/share/zoneinfo
