storage:
  dbPath: /data/db
  wiredTiger:
    engineConfig:
      cacheSizeGB: 1.5
      journalCompressor: zlib
systemLog:
  destination: file
  path: /dev/stdout
  logAppend: true
net:
  port: 27017
  bindIp: 0.0.0.0
security:
  authorization: enabled
